apiVersion: v1
kind: Service
metadata:
  name: svc-complete-production-e2e-deployment
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: complete-production-e2e-deployment